export const INIT_GAME = 'INIT_GAME';
export const INIT_GAME_SUCCESS = 'INIT_GAME_SUCCESS';
export const INIT_GAME_ERROR = 'INIT_GAME_ERROR';

export const GET_GAME_MOVES = 'GET_GAME_MOVES';
export const GET_GAME_MOVES_SUCCESS = 'GET_GAME_MOVES_SUCCESS';
export const GET_GAME_MOVES_ERROR = 'GET_GAME_MOVES_ERROR';

export const CHOOSE_OPTION = 'CHOOSE_OPTION';

export const GET_WINNER = 'GET_WINNER';
export const GET_WINNER_SUCCESS = 'GET_WINNER_SUCCESS';
export const GET_WINNER_ERROR = 'GET_WINNER_ERROR';